set -g mouse on
set -g extended-keys on
set -g extended-keys-format csi-u
bind -N "Create a new window in current directory" c new-window -c "#{pane_current_path}"
bind -N "Split window vertically in current directory" '"' split-window -v -c "#{pane_current_path}"
bind -N "Split window horizontally in current directory" % split-window -h -c "#{pane_current_path}"

